
DB_SERVER = ''
DB_DATABASE = ''
DB_CONNECTION_STRING = f'DRIVER={{SQL Server}};SERVER={DB_SERVER};DATABASE={DB_DATABASE};Trusted_Connection=yes'

# Configurações do SMTP
SMTP_SERVER = ''
SMTP_PORT = 
SMTP_EMAIL = ''
SMTP_PASSWORD = ''
SMTP_RECIPIENT = ''